---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-rag-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-rag-2 
  name: test-rag-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi